site_name: cstbioinfo Documentation
site_description: Personal bioinformatics tools
site_author: openpaul
site_url: https://openpaul.github.io/customPythonBioinfotools/

repo_name: openpaul/customPythonBioinfotools
repo_url: https://github.com/openpaul/customPythonBioinfotools

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - API Reference:
    - Taxonomy: api/tax.md
    - MSA: api/msa.md
    - Embeddings: api/embeddings.md
  - Examples: examples.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [cstbioinfo]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            extra:
              show_source_link: true
